### ISSUE TITLE
Sugerencia: Pruebas- Junit-LYSTP

### ISSUE THREAD

**Issue by JKGarcia94** [programacion-avanzada/workspace-taller#10]
En el código se nos dan ejemplos prácticos sobre el uso del test con la clase punto y los usos de:  ‘assertEquals’, ‘assertEquals(Con un tercer parámetro)’, ‘assertNotNull’ . Podríamos  mejorar la clase test haciendo mas pruebas con ejemplos de tipos: 'assertTrue' , 'assertFalse', 'assertNotEquals', 'assertArrayEquals' . Asi tener mas referencias y ejemplos sobre como hacer las pruebas

**Comment by delucas** [comment]
¡Está buena la idea!

**Comment by delucas** [comment]
Referido en otro issue
