### ISSUE TITLE
Sugerencia: Tutorial para instalacion Windows builder - Los Apila Bits

### ISSUE THREAD

**Issue by coloco19** [programacion-avanzada/workspace-taller#11]
Agregar manuales/tutoriales de windows builder
video tutorial para instalar windows builder: https://www.youtube.com/watch?v=ndhFmgzi6io
repaso teorico: http://codejavu.blogspot.com/2014/03/como-crear-interfaces-graficas-en.html
pagina web con tutorial: http://programacion.codeandcoke.com/doku.php?id=bloque4:windowbuilder

**Comment by delucas** [comment]
Todo esto debería ir en un README. ¿En cuál iría? ¿Qué agregarían?
Debería agregarse un texto, de autoría propia, que explique brevemente cómo hacerlo
