### ISSUE TITLE
Sugerencia: JavaFX tutoriales - Los Apila Bits

### ISSUE THREAD

**Issue by coloco19** [programacion-avanzada/workspace-taller#12]
Se sugiere agregar mas informacion sobre JavaFX
tutorial extenso sobre javaFX: https://code.makery.ch/es/library/javafx-tutorial/
tutorial instalación, ejercicios simples y gestores: https://www.youtube.com/watchv=aIAzHzoC2XI&list=PLaxZkGlLWHGUWZxuadN3J7KKaICRlhz5-

**Comment by delucas** [comment]
Todo esto debería ir en un README. ¿En cuál iría? ¿Qué agregarían?
Debería agregarse un texto, de autoría propia, que explique brevemente cómo hacerlo

**Comment by delucas** [comment]
Rechazado por no contestado

**Comment by delucas** [comment]
Referido en otro issue
