### ISSUE TITLE
Agregar README explicando patron state - HenryFor

### ISSUE THREAD

**Issue by agus1355** [programacion-avanzada/workspace-taller#13]
se podria agregar una explicacion sobre como funciona el patron state para el proyecto de mario

**Comment by delucas** [comment]
¿Qué pondrían? Expliquen un poco más, sin escribirlo puntualmente.

**Comment by agus1355** [comment]
La idea seria agregar una breve explicacion del propio patron, con el diagrama UML que se utiliza.
Ademas, para el proyecto de mario, pensaba en agregar un diagrama de estados como el que presentó en la clase, mostrando el pasaje a cada uno de los estados, con una explicacion del mismo.

**Comment by delucas** [comment]
Referido en otro issue
