### ISSUE TITLE
Cambio en clase Estado.java, proyecto patron state - HenryFor

### ISSUE THREAD

**Issue by agus1355** [programacion-avanzada/workspace-taller#14]
Se podria modificar la clase Estado.java, para que se incluyan los atributos de cada estado especifico como estaticos. De esta forma, no se va a instanciar un estado nuevo cada vez que haya un cambio.

**Comment by delucas** [comment]
Me gusta la mejora, pero lo haría como otra versión del mismo proyecto, con un README explicando por qué se hace así.

**Comment by delucas** [comment]
Referido en otro issue
