### ISSUE TITLE
Sugerencia de Mejora: patrones-observer - Los Apila Bits

### ISSUE THREAD

**Issue by AgusFG** [programacion-avanzada/workspace-taller#15]
Se sugiere la mejora del ejemplo de patrones-observer, agregando el diagrama de clases al README.md: 

![AmongUsDiagrama](https://user-images.githubusercontent.com/78041597/120904467-d59dac00-c622-11eb-8bef-f7f65928fbc4.JPG)

Para el ejemplo: https://github.com/programacion-avanzada/workspace-taller/tree/master/patrones-observer

**Comment by delucas** [comment]
Me gusta el diagrama, pero utilicemos plantuml, que es la herramienta que estamos empleando.

**Comment by delucas** [comment]
Referido en otro issue
