### ISSUE TITLE
FRES-GANG Sugerencia 1 JavaFX Tutorial

### ISSUE THREAD

**Issue by FelixSolay** [programacion-avanzada/workspace-taller#18]
Agregar estos tutoriales de JavaFX para contribuir al aprendizaje de estos conceptos

https://www.youtube.com/watch?v=9XJicRt_FaI
https://es.slideshare.net/NormanEnmanuel/tutorial-javafxprimerospasos

**Comment by delucas** [comment]
Esto debería ir en un README, con algún ejemplo.
¿El issue contempla eso?

**Comment by delucas** [comment]
Rechazado por no contestado

**Comment by delucas** [comment]
Referido en otro issue
