### ISSUE TITLE
Sugerencia: Explicación del patron observer - HenryFor

### ISSUE THREAD

**Issue by lbrandoli** [programacion-avanzada/workspace-taller#19]
Se podría agregar:

Observer es un patrón de diseño de comportamiento que te permite definir un mecanismo de suscripción para notificar a varios objetos sobre cualquier evento que le suceda al objeto que están observando.
El objeto que tiene un estado interesante suele denominarse sujeto o notificador.  El resto de los objetos que quieren conocer los cambios en el estado del notificador, se denominan suscriptores.

El patrón observer se puede utilizar cuando:
-Los cambios en el estado de un objeto puedan necesitar cambiar otros objetos y el grupo de objetos sea desconocido de antemano o cambie dinámicamente.
-Los objetos de una aplicación deban observar a otros, pero sólo durante un tiempo limitado o en casos específicos.

También se podría agregar la siguiente imagen:
http://www3.uji.es/~belfern/Docencia/Presentaciones/ProgramacionAvanzada/Tema2/imagenes/observer.png

**Comment by delucas** [comment]
Me gusta la idea... ¿el texto es de autoría propia?
El diagrama debería ser uno propio, utilizando la herramienta plantuml (como en otros ejemplos de este mismo repo)

**Comment by lbrandoli** [comment]
Hola profe! Para el texto fui sacando fragmentos y basándome en el libro
“Sumérgete en los patrones de diseño” de Alexander Shvets. Respecto a la
imagen... utilizo plantuml para hacerla y se la envío por este medio o
edito el issue con la nueva imagen?

**Comment by delucas** [comment]
Por ahora no lo ejecuten, en una nueva iteración organizaremos el trabajo.
Gracias!

**Comment by delucas** [comment]
Referido en otro issue
