### ISSUE TITLE
[NovaSoft] Agregar READ ME en proyecto patrones-state

### ISSUE THREAD

**Issue by leobaranda** [programacion-avanzada/workspace-taller#20]
Se sugiere sumar un READ ME donde se explique el patron en cuestion, cómo funciona y cuál es el proposito de usarlo, cuales son las ventajas y desventajas de su implementación. También, para su mejor comprensión, sumar el diagrama UML de un patrón State y nombrar ejemplos concretos.

**Comment by delucas** [comment]
Me gusta la idea. ¿Qué ejemplos concretos nombrarían?

**Comment by delucas** [comment]
No fue contestado

**Comment by delucas** [comment]
Referido en otro issue
