### ISSUE TITLE
Sugerencia: agregar README de Swing - Henry For

### ISSUE THREAD

**Issue by tomasserravento** [programacion-avanzada/workspace-taller#21]
Sugerimos agregar un archivo README explicando que es Swing, como funciona y consejos utiles para usarlo.

https://github.com/programacion-avanzada/workspace-taller/tree/master/swing-basico

**Comment by delucas** [comment]
Me gusta la idea, ¿qué consejos escribirían? ¿Tienen algo en mente?

**Comment by delucas** [comment]
Rechazado por no contestado

**Comment by delucas** [comment]
Referido en otro issue
