### ISSUE TITLE
Agregar README explicando Hibernate - HenryFor

### ISSUE THREAD

**Issue by AxelJoelCascasi** [programacion-avanzada/workspace-taller#22]
**README**

**¿Qué es Hibernate?**
_Hibernate es una herramienta de mapeo objeto-relacional (ORM) bajo licencia GNU LGPL para Java, que facilita el mapeo de atributos en una base de datos tradicional, y el modelo de objetos de un aplicación mediante archivos declarativos o anotaciones en los beans de las entidades que permiten establecer estas relaciones._
**¿Cómo funciona Hibernate?**
_En la mayoría de programas actuales existen dos modelos de datos que coexisten: el usado en la memoria de la computadora (orientación a objetos), y el usado en las bases de datos (modelo relacional). Hibernate busca solucionar el problema de la diferencia entre ambos modelos. Para lograr esto, nos permite detallar cómo es su modelo de datos, qué relaciones existen y qué forma tienen mediante un documento XML, o mediante anotaciones donde corresponde un atributo de una clase, con una columna de una tabla._

![que-es-java-hibernate-por-que-usarlo-02](https://user-images.githubusercontent.com/48626905/120906550-b6a61680-c630-11eb-9411-a715fe11ef2b.jpg)

**Comment by AxelJoelCascasi** [comment]
Ademas, agregamos un video de como configurarlo en eclipse: https://www.youtube.com/watch?v=i8M2atUuaHk

**Comment by delucas** [comment]
El texto debería ser propio. ¿Pueden hacer una breve explicación propia?

**Comment by AxelJoelCascasi** [comment]
### **README**

Hibernate es un Framework  que lo que busca es agilizar la relacion entre la aplicación y la base de datos. Es recomendable que a la hora de utilizarlo tengamos algunos conocimientos sobre base de datos y  SQL.
Hibernate permite a la aplicación manipular los datos de la base de datos operando sobre objetos, con todas las características de la Programación Orientada a Objetos.
Una de las ventajas de utilizar este Framework es que es muy fácil de adaptar a distintos motores de base de datos, ya que para esto solo  alcanza con cambiar una linea de un fichero de conexión.

Tenemos distintos objetos en Hibernate :

- **Objeto de Configuración Hibernate**: El objeto de configuración es el primer objeto de Hibernate y generalmente se crea una sola vez durante la inicialización de la aplicación. Este objeto se encarga de establecer las configuraciones y propiedades y nos entrega 2 componentes claves , por un lado  la Conexión de base de datos y por el otro la Configuración de Mapeo Clase.
- **Objetivo SessionFactory:** Objeto de configuración se utiliza para crear un objeto SessionFactory para la aplicación que utiliza el archivo de configuración suministrada, y permite un objeto Session ser ejecutado.
- **Objeto Session**:Se utiliza para obtener una conexión física con una base de datos.
- **Objeto Query**: Objetos de consulta utilizan SQL o Hibernate Query Language (HQL) cadena para recuperar datos de la base de datos y crear objetos. 
- **Objeto Criteria**: Los objetos Criteria se utilizan para crear y ejecutar consultas con objetos y recuperar objetos.

![image](https://user-images.githubusercontent.com/48626905/121784336-dc2fa480-cb89-11eb-99e9-32af2e6188b1.png)

Para mas información acerca de el uso de las base de datos les dejamos este link : https://www.youtube.com/watch?v=bW-NYf606fM
Para configurar Hibernate en eclipse : https://www.youtube.com/watch?v=i8M2atUuaHk&t=3s

**Comment by AxelJoelCascasi** [comment]
profe , ahi lo explique con mis palabras, igualmente se me complica entender algunas cosas y saber bien en que hacer foco a la hora de explicarlo, por eso comente cual es el objetivo y los objetos que nos proporciona el framework.

**Comment by delucas** [comment]
Está bien, en breve cuando asignemos estos temas ya lo van a tener sabido para ejecutarlo finalmente

**Comment by AxelJoelCascasi** [comment]
buenisimo, gracias!
