### ISSUE TITLE
Sugerencia: agregar README de Sockets - Henry For

### ISSUE THREAD

**Issue by tomasserravento** [programacion-avanzada/workspace-taller#23]
Sugerimos agregar un archivo README explicando informacion basica sobre cliente-servidor.

https://github.com/programacion-avanzada/workspace-taller/tree/master/sockets-basico

**Comment by delucas** [comment]
El texto debería ser de autoría propia... y tener enlaces a fuentes confiables.
Me gusta la idea, y que tuviera algún diagrama explicativo también suma.

**Comment by AxelJoelCascasi** [comment]
### README

### _Sockets_
Los sockets son un sistema de comunicación entre procesos de diferentes máquinas de una red. Más exactamente, un socket es un punto de comunicación por el cual un proceso puede emitir o recibir información.

los sockets utilizan el protocolos TCP (Transfer Contro Protocol) ,que es usado para comunicaciones entre redes y  permite que un equipo pueda comunicarse en una red, además utiliza el de datagramas UDP (User Datagram Protocol),  Un datagrama es un paquete de datos que constituye el mínimo bloque de información en una red de conmutación por datagramas. Este protocolo permite el envío de datagramas a través de la red sin que se haya establecido previamente una conexión.
Por otro lado utilizando una serie de primitivas se puede establecer el punto de comunicación para escuchar, escribir, etc...

A continuacion veremos un diagrama del funcionamiento de una conexión de sockets :
![Captura de pantalla 2021-06-15 172154](https://user-images.githubusercontent.com/48626905/122118267-39339080-cdfe-11eb-8140-e12340a5520c.jpg)

Documentacion sockets : https://docs.oracle.com/javase/7/docs/api/java/net/Socket.html

Ademas, adjuntamos un video de youtube en donde hay una pequeña introducción al tema : https://www.youtube.com/watch?v=L0Y6hawPB-E
