### ISSUE TITLE
Sugerencia: patrones-observer [NovaSoft]

### ISSUE THREAD

**Issue by omarquispe95** [programacion-avanzada/workspace-taller#25]
Se podria explicar como funciona el patron, falta un diagrama de clases de ejemplo, tambien los pro y contras que tiene este patron

**Comment by delucas** [comment]
Mayormente esa información se puede acceder desde enlaces externos.
Lo que sumaría es agregar esos enlaces, y explicar el ejemplo dado.

**Comment by delucas** [comment]
Referido en otro issue
