### ISSUE TITLE
[Mick-rosoft] Sugerencia: Organización Carpetas

### ISSUE THREAD

**Issue by thomascu-py** [programacion-avanzada/workspace-taller#27]
Creemos que seria mejor agrupar los proyectos por tema:

-  Pruebas:
          -Junit
       
-  Codegolf

-  Patrones:
          -State
          -Observer
- Interfaz:
          -Swing
          -Graphics       
- Networking:
          -Sockets

**Comment by delucas** [comment]
Me gusta la idea. Deberíamos proponer una estructura concreta
