### ISSUE TITLE
[Mick-rosoft] Sugerencia: Agregar ejemplo Codegolf Fizzbuzz

### ISSUE THREAD

**Issue by thomascu-py** [programacion-avanzada/workspace-taller#28]
Sumar un proyecto con el ejemplo visto en clase del ejercicio Fizzbuzz.
Metodo:
for (int i = 1; i <= 100; i++) {
            if (i % 3 == 0 && i % 5 == 0)
                System.out.println("fizzbuzz ");
            else if (i % 3 == 0)
                System.out.print("fizz ");
            else if (i % 5 == 0) 
                System.out.print("buzz ");
            else
                System.out.print(i + " "); 
        }

**Comment by delucas** [comment]
¿Es esa la implementación hecha con code golf? ¿Sería un proyecto aparte?
¿Cómo lo harían?

**Comment by delucas** [comment]
Rechazado por no contestado

**Comment by delucas** [comment]
Referido en otro issue
