### ISSUE TITLE
[Mick-rosoft] Sugerencia Junit PuntoTest.java

### ISSUE THREAD

**Issue by thomascu-py** [programacion-avanzada/workspace-taller#29]
Hola buenas noches, vimos que en el ejemplo que hay actualmente no se utiliza annihilate por eso creemos que se podría agregar un caso en donde si se utilice. Para que quede explicito y se entienda mejor donde si hace falta utilizarlo.

https://github.com/programacion-avanzada/workspace-taller/blob/master/pruebas-junit/test/edu/unlam/taller/pruebas/PuntoTests.java

**Comment by delucas** [comment]
Me gusta la idea, pero ¿qué proponen? Debería ser un ejemplo distinto, me parece.

**Comment by delucas** [comment]
Rechazado por no contestado

**Comment by delucas** [comment]
Referido en otro issue
