### ISSUE TITLE
[Mick-rosoft] Sugerencia agregar tutorial para aprender a usar GitHub

### ISSUE THREAD

**Issue by nicolasMannarino** [programacion-avanzada/workspace-taller#30]
Se podría agregar un tutorial parecido a este https://guides.github.com/activities/hello-world/, en castellano, donde se explique bien las funciones básicas de  GitHub.

**Comment by delucas** [comment]
Esto excede al temario del taller, pero podría incorporarse como un enlace en loom.
Propónganlo como sugerencia allí por favor.
