### ISSUE TITLE
[Appol] Agregar más ejemplos para el uso de Synchronized

### ISSUE THREAD

**Issue by ManuelR-D** [programacion-avanzada/workspace-taller#33]
Actualmente sólo el proyecto de Threads tiene el uso de la palabra reservada synchronized para crear una función entera, sin embargo también se puede crear un bloque de código dentro de una función usando synchronized contra un objeto.

**Comment by delucas** [comment]
Debería ser un proyecto aparte, con ¿qué tema lo sugieren realizar?
¿Qué ejemplo podría ser bueno?
