### ISSUE TITLE
[Appol] Sugerencia de Swing, ventana emergente

### ISSUE THREAD

**Issue by ManuelR-D** [programacion-avanzada/workspace-taller#34]
Agregar un ejemplo concreto de Swing donde haya un cambio completo de ventana en la aplicación, es decir, que al apretar un botón se abra una nueva ventana y se deseche la anterior, dejando al usuario sólo con la posibilidad de seguir operando en la nueva ventana.

**Comment by delucas** [comment]
Debería ser un proyecto aparte. Con un README propio

**Comment by delucas** [comment]
Referido en otro issue
