### ISSUE TITLE
[Appol] Sugerencia de Swing, uso de threads con ventanas

### ISSUE THREAD

**Issue by ManuelR-D** [programacion-avanzada/workspace-taller#35]
Estaría bueno dar un uso combinado de Threads y ventanas. Si bien Swing ya corre de manera automática en un hilo separado del cual se invoca, con el conocimiento actual en el proyecto Thread uno podría intentar hacer un wait(); dentro del JFrame de Swing esperando a que ocurra un evento que no es relativo a Swing (que se complete una carga de un archivo, por ejemplo), pero al hacer esto se encontraría con que toda su interfaz gráfica se congela, puesto que corre en un sólo hilo que tras el wait() quedó suspendido. Esto usualmente se resuelve invocando otro hilo el cual hace el wait() hasta ser notificado, sin afectar al Frame principal.

**Comment by delucas** [comment]
¿Qué ejemplo concreto podrían proponer?

**Comment by delucas** [comment]
Rechazado por no contestado

**Comment by delucas** [comment]
Referido en otro issue
