### ISSUE TITLE
AGREGAR UN ReadMe a CODEGOLF - ESTHANOSBIEN

### ISSUE THREAD

**Issue by NicolasChavez15** [programacion-avanzada/workspace-taller#5]
ReadMe propuesto:

### CODEGOLF

<p align="center">
<img src="https://cdn.sstatic.net/Sites/codegolf/Img/apple-touch-icon@2.png?v=ed60a1645c65" width="350" alt="accessibility text">
  </p>

_¿Qué es CodeGolf?_
CodeGolf es un tipo de competencia de programación en la que los participantes se esfuerzan por lograr el código fuente más corto posible que implemente un determinado algoritmo. Los desafíos y torneos de golf de código también se pueden nombrar con el lenguaje de programación utilizado (Java, C++, C#, Ruby, Phyton).

_¿De dónde salió el termino CodeGolf?_
El término "CodeGolf " se deriva de la similitud de su objetivo con el del golf convencional, donde los participantes buscan lograr la puntuación más baja posible, en lugar de la más alta, como es el estándar en la mayoría de los deportes y sistemas de puntuación de juegos. Mientras que los jugadores de golf convencionales intentan minimizar el número de golpes necesarios para completar el juego, los participantes de CodeGolf ponen su inteligencia y audacia al servicio de reducir el número de golpes de tecla necesarios para escribir el programa.

_Algunos ejercicios para empezar a pensar_
**1)	Números primos**
Imprima todos los números primos del 1 al 100 inclusive, cada uno en su propia línea.

**2)	Divisores**
Un número es divisor de otro número si se puede dividir sin resto.
Imprime los divisores positivos de cada número del 1 al 100 inclusive, en su propia línea, con cada divisor separado por un espacio.

**3)	Números malignos**
Un número maligno es un número no negativo que tiene un número par de 1 en su expansión binaria.
Imprime todos los números malignos del 0 al 50 inclusive, cada uno en su propia línea.

FUENTES DE INFORMACIÓN
https://en.wikipedia.org/wiki/Code_golf
https://meta.stackexchange.com/questions/20736/what-is-code-golf-on-stack-overflow

FUENTE DE EJERCICIOS PROPUESTOS
https://code.golf/

**Comment by delucas** [comment]
Habría que agregar la fuente de esa información, o que sea creación propia.

**Comment by NicolasChavez15** [comment]
Profe, realice la correccion solicitada.
Saludos

**Comment by NicolasChavez15** [comment]
Profe, disculpe. Cerre el issue desde el botón "Close", y entiendo que no es correcto. Se podra reabrir?

**Comment by delucas** [comment]
Reabierto

**Comment by delucas** [comment]
Referido en otro issue
