### ISSUE TITLE
Agregar README a patrones-state

### ISSUE THREAD

**Issue by camilalopezbisio** [programacion-avanzada/workspace-taller#6]
# Patrón State

## ¿Para qué utilizar el patrón de diseño State?

**_State_** es un patrón de diseño de comportamiento que permite a un objeto alterar su comportamiento cuando su estado interno cambia, como si el objeto cambiara su clase.

## ¿Cuándo utilizar el patrón de diseño State?

*	Utiliza el patrón **_State_** cuando tengas un objeto que se comporta de forma diferente dependiendo de su estado actual, el número de estados sea enorme y el código específico del estado cambie con frecuencia.
El patrón sugiere extraer todo el código específico del estado y ponerlo dentro de un grupo de clases específicas para poder añadir nuevos estados o cambiar los existentes independientemente entre sí, reduciendo el costo de mantenimiento.
*	Utiliza el patrón cuando tengas una clase contaminada con enormes condicionales que alteran el modo en que se comporta la clase de acuerdo con los valores actuales de los campos de la clase.
El patrón **_State_** permite extraer ramas de esos condicionales a métodos de las clases estado correspondientes. 
*	Utiliza el patrón **_State_** cuando tengas mucho código duplicado por estados similares y transiciones de una máquina de estados basada en condiciones.
El patrón **_State_** permite componer jerarquías de clases de estado y reducir la duplicación, extrayendo el código común y metiéndolo en clases abstractas base.

## Estructura

1. La clase **Contexto** almacena una referencia a uno de los objetos de estado concreto y le delega todo el trabajo específico del estado. El contexto se comunica con el objeto de estado a través de la interfaz de estado. El contexto expone un modificador (setter) para pasarle un nuevo objeto de estado.

2. La interfaz **Estado** declara los métodos específicos del estado. Estos métodos deben tener sentido para todos los estados concretos.

3. Los **Estados Concretos** proporcionan sus propias implementaciones para los métodos específicos del estado. Para evitar la duplicación de código similar a través de varios estados, puede incluirse clases abstractas intermedias que encapsulen algún comportamiento común.

![image](https://user-images.githubusercontent.com/81936254/120879894-04713f00-c59d-11eb-8f62-65b113b12732.png)

### Ventajas

*	Principio de responsabilidad única. Organiza el código relacionado con estados particulares en clases separadas.
*	Principio de abierto/cerrado. Introduce nuevos estados sin cambiar clases de estado existentes o la clase contexto.
*	Simplifica el código del contexto eliminando voluminosos condicionales de máquina de estados.

### Desventajas

*	Aplicar el patrón puede resultar excesivo si una máquina de estados sólo tiene unos pocos estados o raramente cambia.

## Fuente
https://refactoring.guru/es/design-patterns/state

**Comment by delucas** [comment]
Copiado de refactoring.guru.
Está buena la idea de generar un readme, pero debería ser del caso propio, o redacción propia. refactoring.guru puede ser un link dentro de un readme propio.

**Comment by camilalopezbisio** [comment]
Buenas noches profe, rehice el readme para basarlo en el ejemplo de Mario que se usó en el código:

# Patrón State

**_State_** es un patrón de diseño de comportamiento que permite a un objeto alterar su comportamiento cuando su estado interno cambia, como si el objeto cambiara su clase.

## Problema

Se desea recrear al famoso personaje de videojuegos Mario Bros. A lo largo del juego, Mario pasa por diferentes estados dependiendo de las acciones que realice: comer un hongo, tocar una flor o recibir un daño.
Al iniciar el juego, tenemos a un Mario de tamaño _Chiquito_. Si este come un hongo, se convierte en Mario _Grande_; si toca una flor se convierte en Mario _Piromaníaco_; pero si recibe un daño, muere (Mario _Muerto_).
Si Mario _Grande_ toca una flor también se convierte en Mario _Piromaníaco_; pero si come un hongo no le ocurre nada. Si recibe un daño, vuelve a ser Mario _Chiquito_.
Mario _Piromaniaco_ solo puede cambiar de estado al recibir un daño. Esto lo transforma en Mario _Grande_. Ni los hongos ni las flores lo modifican.
Finalmente, Mario _Muerto_ no puede cambiar de estado con ninguna acción.

## Diagrama de Estados

![image](https://user-images.githubusercontent.com/81936254/122144210-621d4b00-ce29-11eb-96ee-f0617e38e680.png)

## Clases

- **Contexto**. Representa el objeto que puede cambiar de estado. Tiene entre sus atributos una referencia al estado actual y le delega todo el trabajo específico del estado. En este ejemplo, ésta sería la clase _Mario_.
- **Estado**. Es la clase base para la generación de los distintos estados. Declara los métodos específicos del estado. Estos métodos deben tener sentido para todos los **Estados Concretos**. Suele ser una clase abstracta para definir comportamientos por defecto que afecten el funcionamiento de todos los estados.
- **Estados Concretos**. Representa un posible estado por el cual el objeto (clase **Contexto**) puede pasar. Hereda de la clase **Estado** y proporciona sus propias implementaciones para los métodos específicos de la clase **Estado**. En el ejemplo, los **Estados Concretos** serían la clase _Chiquito_, _Grande_, _Piromaniaco_ y _Muerto_.

## Diagrama de Clases

![image](https://user-images.githubusercontent.com/81936254/122144350-b1637b80-ce29-11eb-8400-38169ab3a031.png)

## Ventajas y Desventajas

### Ventajas

- Organiza el código separando en clases distintas a cada **Estado Concreto**.
- Permite agregar nuevos estados sin realizar cambios en las clases de estado existentes o la clase **Contexto**.
- Simplifica el código del **Contexto** eliminando los grandes condicionales que realizarían los cambios de estado.

### Desventajas

- Si un objeto tiene sólo unos pocos estados o raramente cambia, aplicar el patrón puede resultar excesivo.

**Comment by delucas** [comment]
Referido en otro issue
