### ISSUE TITLE
Agregar READ.ME a pruebas-junit - ESTHANOSBIEN

### ISSUE THREAD

**Issue by jjlarocheml** [programacion-avanzada/workspace-taller#8]
###  **Pruebas unitarias**
Las pruebas unitarias son una herramienta que tenemos los desarrolladores para verificar que el código que escribimos se comporte de la manera que creemos y que necesitamos. Es un arma fundamental en el desarrollo de software, ampliamente utilizado.
###  ¿Por qué utilizar pruebas unitarias?
- Porque nos permiten automatizar pruebas de código una parte fundamental en el CI/CD.
- Porque nos permiten verificar que los cambios que realizamos, no degradan funcionalidades anteriores.
- Porque nos permiten realizar mejoras al código mas rápido, tenemos tests que nos demuestran que el refactor no altero el normal funcionamiento.
- Porque ademas sirven, entre comillas, como documentación del código (aunque sea necesario realizar documentación por escrita, nos brinda otra vision del funcionamiento).
- Porque nos permiten verificar si nuestro código es mantenible, código donde utilizamos implementaciones y no abstracciones serian imposibles de testear, un test nos mostraría este escenario. 

### Otra gran utilidad de los tests:
En muchas empresas se utiliza una metodología llamada TDD (test driven development), es una metodología en la cual primero escribimos los tests y luego desarrollamos la solución/implementación. Es un punto que suma al momento de buscar trabajo en la industria.

### Buenas prácticas
- Las pruebas deben ser independientes, cualquier cambio en el código fuente no debe afectar los tests.
- Cada test debe probar un único escenario.
- Utilizar inyección de depencias, y al utilizarla utilizar interfaces y no implementaciones.
- Los resultados deben ser consistentes, nos tienen que garantizar que la salida es la esperada.

**Comment by delucas** [comment]
El archivo debería ser README.md
¿El contenido es propio? Si no lo fuera, necesitamos saber la fuente
La idea es buena.

**Comment by jjlarocheml** [comment]
Hola profe, fue autoría propia. Pero use algunas ideas de acá: 
[https://www.yeeply.com/blog/que-son-pruebas-unitarias/](url)

**Comment by delucas** [comment]
Referido en otro issue
