### ISSUE TITLE
[Oscar La Oveja] SUGERENCIA: Reorganizar proyectos

### ISSUE THREAD

**Issue by daniel-dv** [programacion-avanzada/workspace-taller#9]
Mejorar la organización de los directorios en el workspace del taller, separando los proyectos en los temas vistos a lo largo del taller, por ejemplo:

1. Pruebas:
-          JUnit
2. Patrones: 
-          Observer
-          State

3. Graficos:
-          Swing
-          Graphics

Etc...

**Comment by delucas** [comment]
¡Me gusta la idea!
